
name: IST_DL21
dependencies:
  - python=3.8
  - numpy
  - pillow
  - scikit-learn
  - pytorch 
  - torchvision
  - huggingface::transformers
  - notebook
  - nb_conda_kernels
  - matplotlib
  - pip
  - pandas
  - pip:
    - timm
